---
force: true
---

services:
  dev-{{ project_name | kebab_case }}-backend-rdb:
    image: dev-{{ project_name | kebab_case }}-backend-rdb:${GIT_BRANCH:-unknown}
    hostname: dev-{{ project_name | kebab_case }}-backend-rdb
    container_name: dev-{{ project_name | kebab_case }}-backend-rdb
    build:
      context: ../../../../
      dockerfile: ./{{ project_name | kebab_case }}/docker/backend/rdb/Dockerfile
      target: dev
      args:
        - ENVIRONMENT=dev
        - PROJECT={{ project_name | kebab_case }}
        - ROLE=backend
        - SERVICE=rdb
        - GIT_BRANCH=${GIT_BRANCH:-unknown}
        - USER_NAME={{ '${' ~ project_name | upper_snake_case }}_USER_NAME:-{{ project_name | kebab_case }}}
        - MYSQL_VERSION={{ '${' ~ project_name | upper_snake_case }}_MYSQL_VERSION:-8.0}
    depends_on:
      dev-{{ project_name | kebab_case }}-common-ubuntu:
        condition: service_started
        required: false
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD={{ '${' ~ project_name | upper_snake_case }}_MYSQL_ROOT_PASSWORD}
      - MYSQL_REPLICA_PASSWORD={{ '${' ~ project_name | upper_snake_case }}_MYSQL_REPLICA_PASSWORD}
    ports:
      - 3306:3306
      - 33060:33060
    volumes:
      - type: bind
        source: ../../../{{ '${' ~ project_name | upper_snake_case }}_APP_DIR:-app}/{{ '${' ~ project_name | upper_snake_case }}_BACKEND_PROJECT:-backend}/infra/migration
        target: /home/{{ '${' ~ project_name | upper_snake_case }}_USER_NAME:-{{ project_name | kebab_case }}}/migration
      - type: volume
        source: dev-{{ project_name | kebab_case }}-backend-rdb-volume
        target: /var/lib/mysql
    init: true
    tty: true
    stdin_open: true
    networks:
      - dev-{{ project_name | kebab_case }}-backend-network
    profiles:
      - dev
      - dev-{{ project_name | kebab_case }}
      - dev-{{ project_name | kebab_case }}-backend
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p{{ '${' ~ project_name | upper_snake_case }}_MYSQL_ROOT_PASSWORD} | grep -q 'mysqld is alive'",
        ]
      interval: 1s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  dev-{{ project_name | kebab_case }}-backend-network:
    name: dev-{{ project_name | kebab_case }}-backend-network

volumes:
  dev-{{ project_name | kebab_case }}-backend-rdb-volume:
    name: dev-{{ project_name | kebab_case }}-backend-rdb-volume
