---
force: true
---

services:
  dev-{{ project_name | kebab_case }}-backend-batch:
    image: dev-{{ project_name | kebab_case }}-backend-batch:${GIT_BRANCH:-unknown}
    hostname: dev-{{ project_name | kebab_case }}-backend-batch
    container_name: dev-{{ project_name | kebab_case }}-backend-batch
    build:
      context: ../../../../
      dockerfile: ./{{ project_name | kebab_case }}/docker/backend/batch/Dockerfile
      target: dev
      args:
        - ENVIRONMENT=dev
        - PROJECT={{ project_name | kebab_case }}
        - ROLE=backend
        - SERVICE=batch
        - GIT_BRANCH=${GIT_BRANCH:-unknown}
        - USER_NAME={{ '${' ~ project_name | upper_snake_case }}_USER_NAME:-{{ project_name | kebab_case }}}
        - APP_DIR={{ '${' ~ project_name | upper_snake_case }}_APP_DIR:-app}
        - BACKEND_PROJECT={{ '${' ~ project_name | upper_snake_case }}_BACKEND_PROJECT:-backend}
        - PORT=8082
        - VSCODE_EXTENSION_JSON=extensions.json
    depends_on:
      dev-{{ project_name | kebab_case }}-common-rust:
        condition: service_started
        required: false
      dev-{{ project_name | kebab_case }}-backend-rdb:
        condition: service_healthy
        required: true
      dev-{{ project_name | kebab_case }}-backend-rdb-replica:
        condition: service_healthy
        required: true
    restart: on-failure
    ports:
      - 8082:8082
    volumes:
      - type: bind
        source: ../../../{{ '${' ~ project_name | upper_snake_case }}_APP_DIR:-app}
        target: /home/{{ '${' ~ project_name | upper_snake_case }}_USER_NAME:-{{ project_name | kebab_case }}}/{{ '${' ~ project_name | upper_snake_case }}_APP_DIR:-app}
      - type: volume
        source: dev-{{ project_name | kebab_case }}-backend-target-volume
        target: /home/{{ '${' ~ project_name | upper_snake_case }}_USER_NAME:-{{ project_name | kebab_case }}}/{{ '${' ~ project_name | upper_snake_case }}_APP_DIR:-app}/{{ '${' ~ project_name | upper_snake_case }}_BACKEND_PROJECT:-backend}/target
    init: true
    tty: true
    stdin_open: true
    networks:
      - dev-{{ project_name | kebab_case }}-backend-network
    profiles:
      - dev
      - dev-{{ project_name | kebab_case }}
      - dev-{{ project_name | kebab_case }}-backend

networks:
  dev-{{ project_name | kebab_case }}-backend-network:
    name: dev-{{ project_name | kebab_case }}-backend-network

volumes:
  dev-{{ project_name | kebab_case }}-backend-target-volume:
    name: dev-{{ project_name | kebab_case }}-backend-target-volume
